### ISSUE TITLE
Return proper error message when service name contains invalid characters

### ISSUE THREAD

**Issue by mammuth** [valar/cli#3]
`valar init --project=x invalid-service-slug`
Should already return a meaningful error message about invalid chars.

instead `valar push` then leads to `Pushing folder: build submit: client: invalid character 'p' after top-level value: 404 page not found`

**Comment by lnsp** [comment]
This should be fixed now. Running the same command prints out `Bad naming scheme: invalid service name: may only contain alphanumerics`.

**Comment by mammuth** [comment]
Cool! :tada:
